version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - e2e

linters:
  enable:
    - forbidigo
    - misspell
    - gofmt
    - goimports
    - errcheck
    - unparam
    - gocritic
    - gosec

settings:
  govet:
    shadow: true
  gofumpt:
    extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

outputs:
  print-linter-name: true